### Получить список объектов недвижимости
GET http://localhost:3000/api/properties

### Получить объект по ID
GET http://localhost:3000/api/properties/ID_ОБЪЕКТА

### Создать объект
POST http://localhost:3000/api/properties
Content-Type: application/json

{
  "name": "Студия 30 м2, Мурино",
  "category": "Квартира",
  "description": "Новая студия с отделкой.",
  "price": 6200000,
  "stock": 1
}

### Частично обновить объект
PATCH http://localhost:3000/api/properties/ID_ОБЪЕКТА
Content-Type: application/json

{
  "price": 6400000,
  "stock": 1
}

### Удалить объект
DELETE http://localhost:3000/api/properties/ID_ОБЪЕКТА
