### Получить все объекты недвижимости
GET http://localhost:3000/api/properties

### Получить объект по ID
GET http://localhost:3000/api/properties/{{id}}

### Создать объект недвижимости
POST http://localhost:3000/api/properties
Content-Type: application/json

{
  "name": "1-комнатная 35 м², Парнас",
  "category": "Квартира",
  "description": "Уютная квартира с видом на парк.",
  "price": 7200000,
  "stock": 1
}

### Обновить объект
PATCH http://localhost:3000/api/properties/{{id}}
Content-Type: application/json

{
  "price": 7500000
}

### Удалить объект
DELETE http://localhost:3000/api/properties/{{id}}

### Swagger UI
GET http://localhost:3000/api-docs
