### Получить список товаров
GET http://localhost:3000/api/products

### Получить товар по ID
GET http://localhost:3000/api/products/PRODUCT_ID

### Создать товар
POST http://localhost:3000/api/products
Content-Type: application/json

{
  "title": "Игровой ноутбук Storm 16",
  "category": "Ноутбуки",
  "description": "Модель с видеокартой RTX и экраном 165 Гц.",
  "price": 119990,
  "stock": 4
}

### Частично обновить товар
PATCH http://localhost:3000/api/products/PRODUCT_ID
Content-Type: application/json

{
  "price": 114990,
  "stock": 6
}

### Удалить товар
DELETE http://localhost:3000/api/products/PRODUCT_ID

### Swagger UI
GET http://localhost:3000/api-docs
