### ПРАКТИКА №3 — Локальная проверка API из задания №2
### Перед запуском поднимите сервер из ../1-2/2 на http://localhost:3000

### 1. Получить список товаров
GET http://localhost:3000/products

### 2. Добавить товар
POST http://localhost:3000/products
Content-Type: application/json

{
  "title": "Клавиатура MechaBoard TKL",
  "price": 8990
}

### 3. Обновить товар
PATCH http://localhost:3000/products/1
Content-Type: application/json

{
  "price": 91990
}

### ПРАКТИКА №3 — Внешний API через локальный прокси
### Перед запуском задайте EXCHANGE_RATE_API_KEY и поднимите server.js на http://localhost:3001

### 4. Проверка состояния прокси
GET http://localhost:3001/health

### 5. Получить все курсы от USD
GET http://localhost:3001/api/exchange-rate/USD

### 6. Получить курс USD -> RUB
GET http://localhost:3001/api/exchange-rate/USD?target=RUB

### 7. Получить курс EUR -> KZT
GET http://localhost:3001/api/exchange-rate/EUR?target=KZT

### 8. Получить курс GBP -> JPY
GET http://localhost:3001/api/exchange-rate/GBP?target=JPY

### 9. Получить курс CNY -> BYN
GET http://localhost:3001/api/exchange-rate/CNY?target=BYN
